CREATE TABLE LOAN_APPLICATION (
    ID VARCHAR(100) PRIMARY KEY,
    APPLICANT_NAME VARCHAR(100) NOT NULL,
    APPLICANT_EMAIL_ID VARCHAR(50) NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    STATUS VARCHAR(15) NOT NULL,
    STATUS_REASON VARCHAR(255),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);